version: "3.9"
services:
  web:
    image: python:3.9-slim
    ports:
      - "5000:5000"
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
